import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

 const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <nav>
        <p>About</p>
      </nav>
      <body className={inter.className}>{children}</body>
      <footer>
        <p>Footer</p>
      </footer>
    </html>
  )
}

export default RootLayout